# Generated by Django 2.1.5 on 2023-10-16 17:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_notifications_url', models.URLField(blank=True, null=True)),
                ('cloud_front_configuration', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='CloudFront Configuration')),
            ],
            options={
                'verbose_name': 'Global Configuration',
            },
        ),
        migrations.CreateModel(
            name='MediaConvertConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='Description')),
                ('settings', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='MediaConvert Configuration')),
            ],
            options={
                'verbose_name': 'MediaConvert Configuration',
                'verbose_name_plural': 'MediaConvert Configurations',
            },
        ),
        migrations.CreateModel(
            name='MediaLiveConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='description')),
                ('source_settings', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Source Settings')),
                ('destination_settings', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Destination Settings')),
                ('encoder_settings', jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Encoder Settings')),
            ],
            options={
                'verbose_name': 'MediaLive Configuration',
                'verbose_name_plural': 'MediaLive Configurations',
            },
        ),
    ]
