# Generated by Django 2.1.5 on 2023-12-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconvertconfiguration',
            name='streamingProtocol',
            field=models.CharField(choices=[('hls', 'HLS'), ('dash', 'DASH')], default='hls', max_length=5, verbose_name='Streaming Protocol'),
        ),
    ]
