# Generated by Django 2.1.5 on 2023-11-29 17:30

import configuration.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaconvertconfiguration',
            name='name',
            field=models.CharField(default='Default', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mediaconvertconfiguration',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, default=configuration.models.get_default_media_convert_configuration_settings, verbose_name='MediaConvert Configuration'),
        ),
        migrations.AlterField(
            model_name='medialiveconfiguration',
            name='destination_settings',
            field=jsonfield.fields.JSONField(blank=True, default=configuration.models.get_default_media_live_destinations_settings, verbose_name='Destination Settings'),
        ),
        migrations.AlterField(
            model_name='medialiveconfiguration',
            name='encoder_settings',
            field=jsonfield.fields.JSONField(blank=True, default=configuration.models.get_default_media_live_encoder_settings, verbose_name='Encoder Settings'),
        ),
        migrations.AlterField(
            model_name='medialiveconfiguration',
            name='source_settings',
            field=jsonfield.fields.JSONField(blank=True, default=configuration.models.get_default_media_live_source_settings, verbose_name='Source Settings'),
        ),
    ]
