# Generated by Django 2.1.5 on 2023-10-16 17:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import jsonfield.fields
import organization.models.channel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Name')),
                ('access_key', models.CharField(max_length=254, verbose_name='Access Key')),
                ('secret_access_key', fernet_fields.fields.EncryptedCharField(max_length=254, verbose_name='Secret Access Key')),
                ('region', models.CharField(choices=[('us-east-1', 'us-east-1'), ('us-east-2', 'us-east-2'), ('us-west-1', 'us-west-1'), ('us-west-2', 'us-west-2'), ('ap-east-1', 'ap-east-1'), ('ap-south-1', 'ap-south-1'), ('ap-northeast-2', 'ap-northeast-2'), ('ap-southeast-1', 'ap-southeast-1'), ('ap-southeast-2', 'ap-southeast-2'), ('ap-northeast-1', 'ap-northeast-1'), ('ca-central-1', 'ca-central-1'), ('eu-central-1', 'eu-central-1'), ('eu-west-1', 'eu-west-1'), ('eu-west-2', 'eu-west-2'), ('eu-west-3', 'eu-west-3'), ('eu-north-1', 'eu-north-1'), ('me-south-1', 'me-south-1'), ('sa-east-1', 'sa-east-1')], max_length=254, verbose_name='Region')),
                ('media_convert_role', models.CharField(max_length=254, verbose_name='MediaConvert Role')),
                ('media_convert_endpoint_url', models.URLField(max_length=254, verbose_name='MediaConvert Endpoint URL')),
                ('media_live_role', models.CharField(max_length=254, verbose_name='MediaLive Role')),
                ('account_id', models.CharField(max_length=64, null=True, verbose_name='Account Id')),
            ],
            options={
                'verbose_name': 'AWS Account',
                'verbose_name_plural': 'AWS Accounts',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Creation Date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('video_transcoding', models.FloatField(default=0, verbose_name='Video Transcoding Minutes')),
                ('audio_transcoding', models.FloatField(default=0, verbose_name='Audio Transcoding Minutes')),
                ('storage', models.FloatField(default=0, verbose_name='Storage (GB)')),
                ('data_transfer', models.FloatField(default=0, verbose_name='Traffic (GB)')),
                ('extras', jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='Extra information')),
            ],
            options={
                'verbose_name': 'Usage Report',
                'verbose_name_plural': 'Usage Reports',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, default=organization.models.channel.get_channel_id, editable=False, max_length=36, unique=True, verbose_name='channel_id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('allowed_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), blank=True, default=list, null=True, size=None, verbose_name='Allowed domains')),
                ('ads_vast_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='VAST URL (ads)')),
                ('detect_adblock', models.BooleanField(default=False, verbose_name='Detect AdBlock?')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Autoplay?')),
                ('cf_id', models.CharField(default='', editable=False, max_length=100, verbose_name='Cf_id')),
                ('cf_domain', models.CharField(default='', editable=False, max_length=100, verbose_name='Cf_domain')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('contact_email', models.CharField(blank=True, default='', max_length=254, verbose_name='Contact Email')),
                ('bucket_name', models.CharField(default='', editable=False, max_length=100, verbose_name='Bucket')),
                ('cf_id', models.CharField(default='', editable=False, max_length=100, verbose_name='Cf_id')),
                ('key_group_id', models.CharField(default='', editable=False, max_length=100, verbose_name='Key_group_id')),
                ('cf_domain', models.CharField(default='', editable=False, max_length=100, verbose_name='Cf_domain')),
                ('config', jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('upload_enabled', models.BooleanField(default=True, verbose_name='Enabled to upload videos')),
                ('traffic_enabled', models.BooleanField(default=True, verbose_name='Data traffic enabled')),
                ('security_enabled', models.BooleanField(default=False, verbose_name='URL security enabled')),
                ('aws_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.AWSAccount', verbose_name='AWS_account')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Business name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('video_transcoding', models.FloatField(default=0, verbose_name='Video Transcoding Minutes')),
                ('audio_transcoding', models.FloatField(default=0, verbose_name='Audio Transcoding Minutes')),
                ('storage', models.FloatField(default=0, verbose_name='Storage (GB)')),
                ('data_transfer', models.FloatField(default=0, verbose_name='Traffic (GB)')),
                ('audio_transcode_configuration', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_transcode_config', to='configuration.MediaConvertConfiguration', verbose_name='Audio transcoding configuration')),
                ('medialive_configuration', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.MediaLiveConfiguration', verbose_name='MediaLive Configuration')),
                ('video_transcode_configuration', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_transcode_config', to='configuration.MediaConvertConfiguration', verbose_name='Video transcoding configuration')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.Plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='channel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='organization.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='organization.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='bill',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='organization.Plan', verbose_name='Plan'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('date', 'organization')},
        ),
    ]
