# Generated by Django 2.1.5 on 2023-11-29 17:30

from django.db import migrations, models
import django.db.models.deletion
import organization.models.organization
import organization.models.plan


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(default=organization.models.organization.get_default_plan_model, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.Plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='audio_transcode_configuration',
            field=models.ForeignKey(default=organization.models.plan.get_default_mediaconvert_configuration, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_transcode_config', to='configuration.MediaConvertConfiguration', verbose_name='Audio transcoding configuration'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='medialive_configuration',
            field=models.ForeignKey(default=organization.models.plan.get_default_medialive_configuration, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.MediaLiveConfiguration', verbose_name='MediaLive Configuration'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='video_transcode_configuration',
            field=models.ForeignKey(default=organization.models.plan.get_default_mediaconvert_configuration, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_transcode_config', to='configuration.MediaConvertConfiguration', verbose_name='Video transcoding configuration'),
        ),
    ]
