# Generated by Django 2.1.5 on 2023-10-16 17:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub_auth.models
import os
import boto3
import json

class Migration(migrations.Migration):
    def create_default_objects(apps, schema_editor):
        AWSAccount = apps.get_model('organization', 'AWSAccount')
        access_key, secret_access_key = os.getenv('AWS_ACCESS_KEY_ID'), os.getenv('AWS_SECRET_ACCESS_KEY')

        media_convert_role_arn = os.getenv('AWS_MEDIA_CONVERT_ROLE')
        media_live_role_arn = os.getenv('AWS_MEDIA_LIVE_ROLE')

        # media_convert_endpoint_url = Migration.get_media_convert_endpoint_url()

        aws_account_defaults = {
            'name': 'Default AWS Account',
            'access_key': access_key,
            'secret_access_key': secret_access_key,
            'media_live_role': media_live_role_arn,
            'media_convert_role': media_convert_role_arn,
            'region': os.environ.get('AWS_DEFAULT_REGION'),
            'account_id': os.environ.get('AWS_ACCOUNT_ID'),
            # 'media_convert_endpoint_url': media_convert_endpoint_url,
            

            # TODO: Add other fields with default values as needed
        }

        AWSAccount.objects.create(**aws_account_defaults)
        
    def create_default_global_settings(apps, schema_editor):
        configuration = apps.get_model('hub_auth', 'Configuration')
        # load cloudfront configuration from file 
        file_path = os.path.join(os.path.dirname(__file__), '../configuration.samples/cloud_front_configuration.json')
        cloud_front_configuration = {}
        with open(file_path) as json_file:
            cloud_front_configuration = json.load(json_file)
        
        configuration.objects.create(
           { "cloud_front_configuration" : cloud_front_configuration}
        )
        
    def create_default_media_convert_settings(apps, schema_editor):
        media_convert_configuration = apps.get_model('hub_auth', 'MediaConvertConfiguration')
        # load media convert configuration from file 
        file_path = os.path.join(os.path.dirname(__file__), '../configuration.samples/media_convert_configuration.json')
        media_convert_configuration = {}
        with open(file_path) as json_file:
            media_convert_configuration = json.load(json_file)
        
        return media_convert_configuration.objects.create(
           { "name" : "Default Media Convert Configuration",
            "description" : "Default Media Convert Configuration",
            "media_convert_configuration" : media_convert_configuration}
        ).id
        
        
    def create_default_media_live_settings(apps, schema_editor):
        media_live_configuration = apps.get_model('hub_auth', 'MediaLiveConfiguration')
        # load media live configuration from file 
        file_path_encoder_settings = os.path.join(os.path.dirname(__file__), '../configuration.samples/media_live_encoder_settings.json')
        file_path_source_settings = os.path.join(os.path.dirname(__file__), '../configuration.samples/media_live_input_attachments.json')
        file_path_destination_settings = os.path.join(os.path.dirname(__file__), '../configuration.samples/media_live_destinations.json')
        media_live_encoder_settings_configuration = {}
        media_live_source_settings_configuration = {}
        media_live_destination_settings_configuration = {}
        with open(file_path_encoder_settings) as json_file:
            media_live_encoder_settings_configuration = json.load(json_file)
        with open(file_path_source_settings) as json_file:
            media_live_source_settings_configuration = json.load(json_file)
        with open(file_path_destination_settings) as json_file:
            media_live_destination_settings_configuration = json.load(json_file)
        
        return media_live_configuration.objects.create(
           { "name" : "Default Media Live Configuration",
            "description" : "Default Media Live Configuration",
            "source_settings" : media_live_source_settings_configuration,
            "destination_settings" : media_live_destination_settings_configuration,
            "encoder_settings" : media_live_encoder_settings_configuration}
        ).id
        
    def create_plan(apps, schema_editor):
        plan = apps.get_model('hub_auth', 'Plan')
        return plan.objects.create(
                {
            "name":'Default Plan',
            " description  ":'Default Plan',
            "media_live_configuration ": Migration.create_default_media_live_settings(),
            " media_convert_configuration ":Migration.create_default_media_convert_settings()
            }
                ).id
    def create_organization(apps, schema_editor):
        organization = apps.get_model('organization', 'Organization')
        organization.objects.create(
                {
            "name":'Default Organization',
            " description  ":'Default Organization',
            "plan ": Migration.create_plan()
            }
                )
            
        
    def create_periodic_tasks(apps, schema_editor):
        PeriodicTask = apps.get_model('djcelery', 'PeriodicTask')
        PeriodicTask.objects.create(
            name='Delete Channels',
            task='hub.tasks.delete_channels',
            interval=3600,
            enabled=True,
        )
        PeriodicTask.objects.create(
            name='Delete Inputs',
            task='hub.tasks.delete_inputs',
            interval=3600,
            enabled=True,
        )
        PeriodicTask.objects.create(
            name='Check Live Cuts',
            task='hub.tasks.check_live_cuts',
            interval=60,
            enabled=True,
        )
        PeriodicTask.objects.create(
            name='Delete Distributions',
            task='hub.tasks.delete_distributions',
            interval=86400,
            enabled=True,
        )
        PeriodicTask.objects.create(
            name='Bill Renewal',
            task='hub.tasks.bill_renewal',
            interval=2592000,
            enabled=True,
        )


        
            
    def get_iam_role_arn(role_name):
        iam_client = boto3.client('iam', region_name=os.environ.get('AWS_DEFAULT_REGION'), aws_access_key_id=os.environ.get('AWS_ACCESS_KEY_ID'), aws_secret_access_key=os.environ.get('AWS_SECRET_ACCESS_KEY'))
        #add access key and secret access key

        try:
            response = iam_client.get_role(RoleName=role_name)
            role_arn = response['Role']['Arn']
        except iam_client.exceptions.NoSuchEntityException:
            print(f"IAM role '{role_name}' not found.")

        return role_arn
        
    
    def get_media_convert_endpoint_url():
        mediaconvert_client = boto3.client('mediaconvert', region_name=os.environ.get('AWS_DEFAULT_REGION'), aws_access_key_id=os.environ.get('AWS_ACCESS_KEY_ID'), aws_secret_access_key=os.environ.get('AWS_SECRET_ACCESS_KEY'))
        
        try:
            response = mediaconvert_client.describe_endpoints()
            print("response")
            print(response)
            endpoint_url = response['Endpoints'][0]['Url']
        except (IndexError, KeyError):
            print("Unable to retrieve MediaConvert endpoint URL.")
            endpoint_url = None

        return endpoint_url
#Default configuration

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Name')),
                ('api_key', models.CharField(default=hub_auth.models.get_key, max_length=100, verbose_name='api key')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.Organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.RunPython(create_default_objects),
       
    ]
    
