# Generated by Django 2.1.5 on 2023-11-22 17:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from organization.models.plan import Plan

class Migration(migrations.Migration):

    initial = True
    
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('hub_auth', 'default'),
        ('organization', '0001_initial'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(default=Plan.objects.get_or_create(
            name='Default Plan',
            )[0].id, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.Plan', verbose_name='Plan'),
        ),
    ]
