# Generated by Django 2.1.5 on 2023-12-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='protocol_type',
            field=models.CharField(default='hls', max_length=5, verbose_name='Protocol Type'),
        ),
    ]
